name: Compile GUI for Ubuntu
# run this job manually
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # used to checkout different branches
      - uses: actions/checkout@v3
        with:
          # checkout my specific branch
          ref: main
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: pip install dependencies
        run: pip install -r requirements.txt
      - name: compile GUI for ubuntu
        run: python -m eel src/python/gui_main.py src/web/ --onefile --noconsole --name excel_uploader_gui_linux --icon=src/assets/logo_condensed.ico
      - name: set Git credentials
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: push executable to branch "executable"
        run: |
          cd dist/
          ls
          git checkout executables
          git add .
          git commit -m "bot pushing linux GUI executable"
          git push origin executable
