name: Compile GUI for Windows
# run this job manually
on: 
  push:
    tags:
      # Push events to every tag including hierarchical tags like v1.0/beta
      - '**'

# Allows you to run this workflow manually too
  workflow_dispatch:
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      # used to checkout different branches
      - uses: actions/checkout@v3
        with:
          # checkout my specific branch
          ref: main
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: pip install dependencies
        run: pip install -r requirements.txt
      - name: compile GUI for Windows
        run: python -m eel .\src\python\gui_main.py .\src\web\ --onefile --noconsole --clean --name excel_uploader_gui_windows --icon=.\src\assets\logo_condensed.ico

      - uses: actions/upload-artifact@v3
        with:
          # artifact name
          name: CRIPT Excel Uploader Windows Zip
          path: dist/
          if-no-files-found: error
          retention-days: 10
